export const AIRCRAFTS_SUCCESS = "AIRCRAFTS_SUCCESS";
export const AIRCRAFTS_SEARCH = "AIRCRAFTS_SEARCH";
export const AIRCRAFTS_LIMIT = "AIRCRAFTS_LIMIT";
export const LOAD_PROGRESS = "LOAD_PROGRESS";